# Generated by Django 5.1.3 on 2024-12-04 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Zakończone')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Termin wykonania')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej aktualizacji')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Wysoki'), (2, 'Średni'), (3, 'Niski')], default=2, verbose_name='Priorytet')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Kategoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Zadanie',
                'verbose_name_plural': 'Zadania',
                'ordering': ['-priority', 'due_date'],
            },
        ),
    ]
